// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package service

// Injectors from wire.go:

func InitProvider() ServiceProvider {
	capsuleService := ProvideCapsuleService()
	missionService := ProvideMissionService()
	serviceProvider := ProvideServiceProvider(capsuleService, missionService)
	return serviceProvider
}

// wire.go:

// ServiceProvider contains avilable services
type ServiceProvider struct {
	CapsuleService *CapsuleService
	MissionService *MissionService
}

// ProvideServiceProvider creates an instance of ServiceProvider
func ProvideServiceProvider(capsuleService *CapsuleService, missionService *MissionService) ServiceProvider {
	return ServiceProvider{
		CapsuleService: capsuleService,
		MissionService: missionService,
	}
}
